---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawler-ui
  labels:
    app: crawler
    component: crawler-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crawler
      component: crawler-ui
  template:
    metadata:
      name: crawler-ui-pod
      labels:
        app: crawler
        component: crawler-ui
    spec:
      containers:
      - image: jakui/crawler_ui:latest
        name: crawler-ui
        env:
        - name: MONGO
          value: mongo
        - name: MONGO_PORT
          value: "27017"
#        - name: crawler-ui_DATABASE_HOST
#          value: crawler-ui-db
