---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-engine
  labels:
    app: crawler
    component: search-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crawler
      component: search-engine
  template:
    metadata:
      name: search-engine-pod
      labels:
        app: crawler
        component: search-engine
    spec:
      containers:
      - image: jakui/crawler:latest
        name: search-engine
        env:
        - name: MONGO
          value: "mongo"
        - name: RABBITMQ_ERLANG_COOKIE
          value: "mycookie"
        - name: RABBITMQ_DEFAULT_USER
          value: "rabbitmq"
        - name: RABBITMQ_DEFAULT_PASS
          value: "rabbitmq"
