---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawler-ui
  labels:
    app: crawler
    component: crawler-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crawler
      component: crawler-ui
  template:
    metadata:
      name: crawler-ui-pod
      labels:
        app: crawler
        component: crawler-ui
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "pythonapp"
        dapr.io/log-as-json: "true"
    spec:
      containers:
      - image: jakui/crawler_ui:latest
        name: crawler-ui
        env:
        - name: crawler-ui_DATABASE_HOST
          value: crawler-ui-db