---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crawler-ui-srvs
  annotations:
    kubernetes.io/ingress.allow-http: "true" # Разрешаем проброс HTTP
spec:
  ingressClassName: nginx
  rules:
  - host: "crawler.maxx.su"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: crawler-ui-srvs
            port:
              number: 8000
  







