---
apiVersion: v1
kind: Service
metadata:
  name: search-engine-rmq
  labels:
    app: crawler
    component: rabbit
    search-engine-rmq: "true"
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: crawler
    component: rabbit
    search-engine-rmq: "true"
