image: ruby:2.4.2

stages:
  - build
 # - test
  - review
  - deploy

variables:
  DATABASE_URL: 'mongodb://mongo/user_posts'
  

before_script:
 - ls
# - mkdir ~/.kube && cp config ~/.kube/config
 - curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
 - chmod +x ./kubectl
 - mv ./kubectl /usr/local/bin/kubectl
 - kubectl version --client
 - kubectl get po




build_job:
  stage: build
  script:
    - echo 'Building'

#test_unit_job:
#  stage: test
#  script:
#    - echo 'Testing'

#test_integration_job:
#  stage: test
#  script:
#    - echo 'Testing 2'



branch review:
  stage: review
  script: echo "Deploy to $CI_ENVIRONMENT_SLUG"
  environment:
    name: branch/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.example.com
  only:
    - gitlab-ci
  except:
    - master


deploy_dev_job:
  stage: deploy
  script:
    - echo 'Deploy Rabbitmq'
    - kubectl apply -f rabbitmq_rbac.yaml -n dev
    - kubectl apply -f rabbitmq_pv.yaml -n dev
    - kubectl apply -f rabbitmq_pvc.yaml -n dev
    - kubectl apply -f rabbitmq_service.yaml -n dev
    - kubectl apply -f rabbitmq_service_ext.yaml -n dev
    - kubectl apply -f rabbitmq_configmap.yaml -n dev
    - kubectl apply -f rabbitmq_statefulset.yaml -n dev
  environment:
    name: dev
    url: http://dev.example.com





