version: '3.3'
services:
  prometheus:
    image: prom/prometheus
    ports:
      - '9090:9090'
    volumes:
        - prometheus_data:/prometheus
        - ./prometheus.yml:/etc/prometheus/prometheus.yml
        - ./alertmanager/alert.rules:/etc/prometheus/alert.rules
    networks:
      - docker_appnet
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'

  alertmanager: 
     image: prom/alertmanager 
     volumes:
        - ./alertmanager/alertmanager.yml:/alertmanager.yml
     command: 
      - '--config.file=/alertmanager.yml' 
     ports: 
      - 9093:9093 
     networks:
      - docker_appnet
  grafana:
    image: grafana/grafana-oss:8.5.0
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=gfadmin
      - GF_SECURITY_ADMIN_PASSWORD=crawler
    depends_on:
      - prometheus
    networks:
      - docker_appnet  
    ports:
      - 3000:3000

volumes:
  prometheus_data:
  grafana_data:

networks:
  docker_appnet:
    external:
     name: docker_appnet
