version: '3.3'
services:
  fluentd:
    image: opopovich85/fluentd:latest
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - appnet
  elasticsearch:
    image: elasticsearch:8.1.3
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - appnet
    
    
  kibana:
    image: kibana:8.1.3
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

volumes:
  elasticsearch-data:
    driver: local
