version: '3.3'
services:
  fluentd:
    image: opopovich85/fluentd:latest
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - appnet
  #elasticsearch:
  #  image: elasticsearch
  #  expose:
  #    - 9200
  #  ports:
  #    - "9200:9200"
    
    
  #kibana:
  #  image: kibana
  #  ports:
  #    - "5601:5601"

networks:
  appnet:
    driver: bridge
