kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rabbitmq-data
spec:
  storageClassName: rabbitmq-data-sigma
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  # csi:
  #   driver: disk-csi-driver.mks.ycloud.io
  #   fsType: ext4
  #   volumeHandle: epdaiom40681u701lrji
